### ISSUE TITLE
Can't install from npm

### ISSUE THREAD

**Issue by goneplaid** [jquery/jquery-simulate#48]
Here's my npm-debug.log file output:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/Users/shawn/.node/bin/npm',
1 verbose cli   'install',
1 verbose cli   'jquery-simulate' ]
2 info using npm@4.0.5
3 info using node@v6.9.2
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData jquery-simulate
8 silly fetchNamedPackageData jquery-simulate
9 silly mapToRegistry name jquery-simulate
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'jquery-simulate',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'jquery-simulate',
12 silly mapToRegistry   name: 'jquery-simulate',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/jquery-simulate
14 verbose request uri https://registry.npmjs.org/jquery-simulate
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:35:57 PM
17 verbose request id 8be6692d3b1c87d6
18 http request GET https://registry.npmjs.org/jquery-simulate
19 http 200 https://registry.npmjs.org/jquery-simulate
20 verbose headers { server: 'nginx/1.10.1',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'last-modified': 'Thu, 02 Apr 2015 22:12:07 GMT',
20 verbose headers   etag: 'W/"551dbeb7-1a6"',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '248',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Thu, 12 Jan 2017 23:35:54 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-lax8628-LAX',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1484264154.758616,VS0,VE161',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'nginx/1.10.1',
21 silly get     'content-type': 'application/json',
21 silly get     'last-modified': 'Thu, 02 Apr 2015 22:12:07 GMT',
21 silly get     etag: 'W/"551dbeb7-1a6"',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '248',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Thu, 12 Jan 2017 23:35:54 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-lax8628-LAX',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1484264154.758616,VS0,VE161',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving jquery-simulate to /Users/shawn/.npm/registry.npmjs.org/jquery-simulate/.cache.json
23 verbose correctMkdir /Users/shawn/.npm correctMkdir not in flight; initializing
24 verbose makeDirectory /Users/shawn/.npm creation not in flight; initializing
25 silly makeDirectory /Users/shawn/.npm uid: 501 gid: 20
26 verbose stack TypeError: Cannot convert undefined or null to object
26 verbose stack     at pickVersionFromRegistryDocument (/Users/shawn/.node/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
26 verbose stack     at /Users/shawn/.node/lib/node_modules/npm/node_modules/iferr/index.js:13:50
26 verbose stack     at /Users/shawn/.node/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
26 verbose stack     at saved (/Users/shawn/.node/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
26 verbose stack     at /Users/shawn/.node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:261:18
26 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
27 verbose cwd /Users/shawn/dev/scootaloo
28 error Darwin 14.5.0
29 error argv "/usr/local/bin/node" "/Users/shawn/.node/bin/npm" "install" "jquery-simulate"
30 error node v6.9.2
31 error npm  v4.0.5
32 error Cannot convert undefined or null to object
33 error If you need help, you may report this error at:
33 error     <https://github.com/npm/npm/issues>
34 verbose exit [ 1, true ]
```

**Comment by BVaughanNI** [comment]
I am also having this problem, so I'll +1 this issue.

**Comment by micky2be** [comment]
Can someone from the organization takes 2 minutes to publish it on npm please

**Comment by mgol** [comment]
@micky2be I'd be happy to take over the npm package. I am one of the jQuery maintainers. Can you transfer the package to me? (mgol on npm).

**Comment by micky2be** [comment]
@mgol done. Let me know if you encounter any issues.
